# "org" ensures this Service is used with the correct Serverless Framework
# Access Key.
org: marty8zhang
# "app" enables Serverless Framework Dashboard features and sharing them with
# other Services.
app: demo-nestjs-serverless
# "service" is the name of this project. This will also be added to your AWS
# resource names.
service: demo-nestjs-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
#  timeout: 10

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayCognitoAuthorizer
      - http:
          method: ANY
          path: '{proxy+}'
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayCognitoAuthorizer
    # Gives the Lambda function access to resources in the AWS VPC, which hosts
    # a MongoDB server within a private EC2 instance.
    vpc:
      subnetIds:
        - ${env:AWS_VPC_SUBNET_ID_PUBLIC_ONE}
        - ${env:AWS_VPC_SUBNET_ID_PUBLIC_TWO}
      securityGroupIds:
        - ${env:AWS_SG_ID_LAMBDA}
    environment:
      DB_HOST: ${self:custom.db-credentials.host}
      DB_PORT: ${self:custom.db-credentials.port}
      DB_USERNAME: ${self:custom.db-credentials.username}
      DB_PASSWORD: ${self:custom.db-credentials.password}
      DB_DBNAME: ${self:custom.db-credentials.dbname}
      EGGHDZ_V1_ADDRESS: ${env:AWS_EC2_IP_PRIVATE_EGGHDZ_V1}

package:
  # AWS Lambda 101: Reduce the upload package size by excluding unnecessary
  # folders/files to prevent the error of
  # "Unzipped size must be smaller than 262144000 bytes".
  # In this demo project, only files in `dist/` are needed.
  patterns:
    - '!./**'
    - 'dist/**'

resources:
  # Refer to: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
  # Note: In a real-world scenario, most infrastructure resources like below
  # should be managed separately, e.g., in a separate `serverless.yml` or even a
  # separate repository. They're only included here for the purposes of demoing
  # and providing a quicker way to spin up the demo environment.
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: admin_only
              Priority: 1
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        AliasAttributes:
          - email
          - preferred_username
        AutoVerifiedAttributes:
          - email
        # Deletion protection is good for production, but with it being active,
        # manually disabling this feature will be needed before running
        # `serverless remove`, which then defeats the purposes of quick demoing.
        # DeletionProtection: ACTIVE
        EnabledMfas:
          # It doesn't seem there's an easy way to bypass relevant SMS
          # configurations with `SMS_MFA` included here. This CloudFormation
          # behaviour is different from when creating a user pool via the AWS
          # console (UI), where the console allows a partial configuration by
          # only assigning an IAM role to finish user pool creation.
          # - SMS_MFA
          - SOFTWARE_TOKEN_MFA
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        MfaConfiguration: OPTIONAL
        Schema:
          - Name: updated_at
            Required: true
          - AttributeDataType: String
            Mutable: true
            Name: hobbies
            Required: false
            StringAttributeConstraints:
              MaxLength: '2048'
              MinLength: '1'
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate:
            - email
        UsernameConfiguration:
          CaseSensitive: false
        UserPoolName: ${sls:stage}-demo-nestjs-serverless
        UserPoolTags:
          test: ''
          demo: ''
    CognitoUserPoolAppClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        AccessTokenValidity: 1
        AuthSessionValidity: 3
        ClientName: demo-nestjs-serverless
        EnableTokenRevocation: true
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_PASSWORD_AUTH
        GenerateSecret: false
        IdTokenValidity: 1
        PreventUserExistenceErrors: ENABLED
        RefreshTokenValidity: 7
        TokenValidityUnits:
          AccessToken: hours
          IdToken: hours
          RefreshToken: days
        UserPoolId: !Ref CognitoUserPool
    CognitoUserPoolDemosUser:
      Type: AWS::Cognito::UserPoolUser
      Properties:
        DesiredDeliveryMediums: [ ]
        UserAttributes:
          - Name: custom:hobbies
            Value: Coding,Reading
          - Name: email
            Value: ${env:AWS_COGNITO_USER_POOL_EMAIL}
          - Name: email_verified
            Value: "true"
          - Name: preferred_username
            Value: ${env:AWS_COGNITO_USER_POOL_USERNAME}
        Username: ${env:AWS_COGNITO_USER_POOL_USERNAME}
        UserPoolId: !Ref CognitoUserPool
    ApiGatewayCognitoAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        Name: CognitoAuthoriser
        ProviderARNs:
          - !Join
            - ''
            - - 'arn:aws:cognito-idp'
              - ':'
              - ${self:provider.region}
              - ':'
              - !Ref AWS::AccountId
              - ':userpool/'
              - !Ref CognitoUserPool
        # `ApiGatewayRestApi` is Serverless Framework's default Rest API logical
        # id.
        RestApiId: !Ref ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
    # The following resources provide Internet access to a private subnet by
    # doing these things (see `docs/public-nat-gateway.drawio`):
    #   - Create a public NAT gateway (`PublicNatGateway`) in an existing public
    #     subnet.
    #   - `PublicNatGatewayEIP` allows the gateway to be allocated with a public
    #     IP address, hence make it public.
    #   - Create a network route table (`RouteTableUsingPublicNatGateway`) in an
    #     existing VPC.
    #   - Create a network route (`InternetAccessRoute`), which points to the
    #     public NAT gateway, within the route table.
    #   - `SubnetRouteTableAssociation` associates the route table with an
    #     existing private subnet which previously doesn't have Internet access.
    # Note: All subnets mentioned here belong to the same VPC.
    PublicNatGateway:
      Type: AWS::EC2::NatGateway
      Properties:
        SubnetId: ${env:AWS_VPC_SUBNET_ID_PUBLIC_TWO}
        AllocationId: !GetAtt PublicNatGatewayEIP.AllocationId
    PublicNatGatewayEIP:
      Type: AWS::EC2::EIP
      Properties: { }
    RouteTableUsingPublicNatGateway:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: ${env:AWS_VPC_ID}
    InternetAccessRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId: !Ref RouteTableUsingPublicNatGateway
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId: !Ref PublicNatGateway
    SubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTableUsingPublicNatGateway
        SubnetId: ${env:AWS_VPC_SUBNET_ID_PRIVATE_ONE}

custom:
  db-credentials: ${aws:ssm:/aws/reference/secretsmanager/${env:AWS_SM_SECRET_ID_DATABASE}}
  serverless-offline:
    # A workaround for the "Cannot GET/POST/... null" issue when hitting the
    # root url. With this flag turn on, there'll be no stage tag in the URLs
    # when the service is started with `serverless offline`. E.g., with the
    # flag off (default), `GET http://localhost:3000/dev/`; with it on,
    # `GET http://localhost:3000/`.
    # See:
    #   - https://github.com/dougmoscrop/serverless-http/issues/86
    #   - https://github.com/dherault/serverless-offline?tab=readme-ov-file#noprependstageinurl
    noPrependStageInUrl: true
